[package]
name = "imgui-software-renderer"
version = "0.1.0"
authors = ["dbr <dbr.onix@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.5"
imgui = "0.7.0"